/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ADMIN
 */
public class CustomerDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CustomerDashboard.class.getName());

    /**
     * Creates new form CustomerDashboard
     */
    public CustomerDashboard() {
        initComponents();
        this.setLocation(300, 150); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeHomePage = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        bookService = new javax.swing.JButton();
        viewStatus = new javax.swing.JButton();
        payment = new javax.swing.JButton();
        payment1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcomeHomePage.setBackground(new java.awt.Color(0, 0, 0));
        welcomeHomePage.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        welcomeHomePage.setForeground(new java.awt.Color(255, 102, 102));
        welcomeHomePage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeHomePage.setText("Welcome Customer");
        welcomeHomePage.setOpaque(true);
        getContentPane().add(welcomeHomePage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 42));

        logout.setBackground(new java.awt.Color(255, 153, 204));
        logout.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        logout.setForeground(new java.awt.Color(51, 51, 51));
        logout.setText("Logout");
        logout.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        logout.addActionListener(this::logoutActionPerformed);
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 256, 185, 37));

        bookService.setBackground(new java.awt.Color(153, 204, 255));
        bookService.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bookService.setText("Book Service");
        bookService.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bookService.addActionListener(this::bookServiceActionPerformed);
        getContentPane().add(bookService, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 48, 185, 34));

        viewStatus.setBackground(new java.awt.Color(153, 204, 255));
        viewStatus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewStatus.setText("View Status");
        viewStatus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewStatus.addActionListener(this::viewStatusActionPerformed);
        getContentPane().add(viewStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 185, 34));

        payment.setBackground(new java.awt.Color(153, 204, 255));
        payment.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        payment.setText("Payment");
        payment.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        payment.addActionListener(this::paymentActionPerformed);
        getContentPane().add(payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 152, 185, 34));

        payment1.setBackground(new java.awt.Color(153, 204, 255));
        payment1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        payment1.setText("Service History");
        payment1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        payment1.addActionListener(this::payment1ActionPerformed);
        getContentPane().add(payment1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 204, 185, 34));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Downloads\\Customer Dashbord 2.jpeg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-190, 0, 810, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bookServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookServiceActionPerformed
        // TODO add your handling code here:
         ServiceBooking bookService = new ServiceBooking ();
         bookService.setVisible(true);
         this.dispose(); // optional
        
    }//GEN-LAST:event_bookServiceActionPerformed

    private void viewStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewStatusActionPerformed
        // TODO add your handling code here:
        ServiceStatusTracking seviceStatus = new ServiceStatusTracking();
        seviceStatus.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_viewStatusActionPerformed

    private void paymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentActionPerformed
        // TODO add your handling code here:
        PaymentPage payment = new PaymentPage();
        payment.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_paymentActionPerformed

    private void payment1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payment1ActionPerformed
        // TODO add your handling code here:
        ServiceHistory history = new ServiceHistory();
        history.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_payment1ActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        // open Customer Login Page
        HomePage home = new HomePage();
        home.setVisible(true);
         this.dispose(); // optional
    }//GEN-LAST:event_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CustomerDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookService;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logout;
    private javax.swing.JButton payment;
    private javax.swing.JButton payment1;
    private javax.swing.JButton viewStatus;
    private javax.swing.JLabel welcomeHomePage;
    // End of variables declaration//GEN-END:variables
}
