/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ADMIN
 */

import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

public class CustomerRegistration extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CustomerRegistration.class.getName());

    /**
     * Creates new form CustomerRegistration
     */
    public CustomerRegistration() {
        initComponents();
        this.setLocation(300, 150); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cFullName = new javax.swing.JLabel();
        cEmail = new javax.swing.JLabel();
        cAddress = new javax.swing.JLabel();
        cMobileNum = new javax.swing.JLabel();
        cPassword = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        mobile = new javax.swing.JTextField();
        full_name = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        registerButton = new javax.swing.JButton();
        registrationForm = new javax.swing.JLabel();
        bookService = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cFullName.setBackground(new java.awt.Color(255, 204, 153));
        cFullName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cFullName.setText("Full Name ");
        cFullName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cFullName.setOpaque(true);
        getContentPane().add(cFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 148, 114, 32));

        cEmail.setBackground(new java.awt.Color(255, 204, 153));
        cEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cEmail.setText("Customer ID");
        cEmail.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cEmail.setOpaque(true);
        getContentPane().add(cEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 98, 114, 32));

        cAddress.setBackground(new java.awt.Color(255, 204, 153));
        cAddress.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cAddress.setText("Address");
        cAddress.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cAddress.setOpaque(true);
        getContentPane().add(cAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 114, 32));

        cMobileNum.setBackground(new java.awt.Color(255, 204, 153));
        cMobileNum.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cMobileNum.setText("Mobile Number");
        cMobileNum.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cMobileNum.setOpaque(true);
        getContentPane().add(cMobileNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 198, 114, 32));

        cPassword.setBackground(new java.awt.Color(255, 204, 153));
        cPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cPassword.setText("Password");
        cPassword.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cPassword.setOpaque(true);
        getContentPane().add(cPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 114, 32));

        id.addActionListener(this::idActionPerformed);
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 217, 32));

        address.addActionListener(this::addressActionPerformed);
        getContentPane().add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 223, 32));

        mobile.addActionListener(this::mobileActionPerformed);
        getContentPane().add(mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 223, 32));

        full_name.addActionListener(this::full_nameActionPerformed);
        getContentPane().add(full_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 217, 32));

        jTextField7.addActionListener(this::jTextField7ActionPerformed);
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 89, 217, 0));
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 223, 32));

        registerButton.setBackground(new java.awt.Color(102, 204, 255));
        registerButton.setForeground(new java.awt.Color(255, 255, 255));
        registerButton.setText("Register");
        registerButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        registerButton.addActionListener(this::registerButtonActionPerformed);
        getContentPane().add(registerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 208, 42));

        registrationForm.setBackground(new java.awt.Color(204, 255, 255));
        registrationForm.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        registrationForm.setForeground(new java.awt.Color(255, 102, 102));
        registrationForm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registrationForm.setText("Customer Registration");
        registrationForm.setOpaque(true);
        getContentPane().add(registrationForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 405, 42));

        bookService.setBackground(new java.awt.Color(204, 204, 255));
        bookService.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bookService.setText("<-- Back ");
        bookService.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bookService.addActionListener(this::bookServiceActionPerformed);
        getContentPane().add(bookService, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 85, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Downloads\\Csutomer registration.jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 540, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void full_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_full_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_full_nameActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed

    
    String cid = id.getText();
    String name = full_name.getText();
    String mob = mobile.getText();
    String pass = String.valueOf(password.getPassword());
    String addr = address.getText();

    if(cid.isEmpty() || name.isEmpty() || mob.isEmpty()
            || pass.isEmpty() || addr.isEmpty()) {

        JOptionPane.showMessageDialog(this,
                "Please Fill All Fields");

        return;
    }

    try {

        Connection con = DBConnection.getConnection();

        String sql = "INSERT INTO customer VALUES(?,?,?,?,?)";

        PreparedStatement pst = con.prepareStatement(sql);

        pst.setInt(1, Integer.parseInt(cid));
        pst.setString(2, name);
        pst.setString(3, mob);
        pst.setString(4, pass);
        pst.setString(5, addr);

        int result = pst.executeUpdate();

        if(result > 0) {

            JOptionPane.showMessageDialog(this,
                    "Registration Successful");

            id.setText("");
            full_name.setText("");
            mobile.setText("");
            password.setText("");
            address.setText("");

        }

        con.close();

    } catch(Exception e) {

        JOptionPane.showMessageDialog(this,
                e.getMessage());

    }// TODO add your handling code here:
        
       
       // open Customer Login Page
        CustomerLogin login = new CustomerLogin();
        login.setVisible(true);
         this.dispose(); // optional

        this.dispose(); // optional
    }//GEN-LAST:event_registerButtonActionPerformed

    private void mobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobileActionPerformed

    private void bookServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookServiceActionPerformed
        // TODO add your handling code here:
        HomePage back = new HomePage ();
        back.setVisible(true);
        this.dispose(); // optional
    }//GEN-LAST:event_bookServiceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CustomerRegistration().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JButton bookService;
    private javax.swing.JLabel cAddress;
    private javax.swing.JLabel cEmail;
    private javax.swing.JLabel cFullName;
    private javax.swing.JLabel cMobileNum;
    private javax.swing.JLabel cPassword;
    private javax.swing.JTextField full_name;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField mobile;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton registerButton;
    private javax.swing.JLabel registrationForm;
    // End of variables declaration//GEN-END:variables
}
