/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ADMIN
 */


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;


public class CustomerLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CustomerLogin.class.getName());

    /**
     * Creates new form CustomerLogin
     */
    public CustomerLogin() {
        initComponents();
        this.setLocation(300, 150); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cMail = new javax.swing.JLabel();
        cPassword = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        cLogin = new javax.swing.JLabel();
        bookService = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cMail.setBackground(new java.awt.Color(255, 204, 153));
        cMail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cMail.setText("Customer ID");
        cMail.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cMail.setOpaque(true);
        getContentPane().add(cMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 82, 114, 32));

        cPassword.setBackground(new java.awt.Color(255, 204, 153));
        cPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cPassword.setText("Password");
        cPassword.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cPassword.setOpaque(true);
        getContentPane().add(cPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 132, 114, 32));

        id.addActionListener(this::idActionPerformed);
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 217, 32));

        password.addActionListener(this::passwordActionPerformed);
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 217, 32));

        loginButton.setBackground(new java.awt.Color(102, 204, 255));
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("Login");
        loginButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loginButton.addActionListener(this::loginButtonActionPerformed);
        getContentPane().add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 208, 42));

        cLogin.setBackground(new java.awt.Color(204, 255, 255));
        cLogin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        cLogin.setForeground(new java.awt.Color(255, 102, 102));
        cLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cLogin.setText("Customer Login ");
        cLogin.setOpaque(true);
        getContentPane().add(cLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 340, 42));

        bookService.setBackground(new java.awt.Color(204, 204, 255));
        bookService.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bookService.setText("<-- Back ");
        bookService.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bookService.addActionListener(this::bookServiceActionPerformed);
        getContentPane().add(bookService, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 85, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Downloads\\Customer Dashbord 2.jpeg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-200, 0, 690, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
        
        String cEmail1 =this.id.getText();
        String cPassword1 = new String (this.password.getPassword());
        
       
        
        
    }//GEN-LAST:event_idActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
//        CustomerDashboard homePage = new CustomerDashboard ();
//        homePage.setVisible(true);
//         this.dispose(); // optional
         
         
         String cid = id.getText();
         String pass = String.valueOf(password.getPassword());

    if(cid.isEmpty() || pass.isEmpty()) {

        JOptionPane.showMessageDialog(this,
                "Please Enter Customer ID and Password");

        return;
    }

    try {

        Connection con = DBConnection.getConnection();

        String sql =
                "SELECT * FROM customer WHERE id=? AND password=?";

        PreparedStatement pst =
                con.prepareStatement(sql);

        pst.setInt(1, Integer.parseInt(cid));
        pst.setString(2, pass);

        ResultSet rs = pst.executeQuery();

        if(rs.next()) {

            JOptionPane.showMessageDialog(this,
                    "Login Successful");

//            // Open Home Page
//            HomePage home = new HomePage();
//            home.setVisible(true);

//            this.dispose();
        CustomerDashboard homePage = new CustomerDashboard ();
        homePage.setVisible(true);
         this.dispose(); // optional



        } else {

            JOptionPane.showMessageDialog(this,
                    "Invalid Customer ID or Password");

        }

        con.close();

    } catch(Exception e) {

        JOptionPane.showMessageDialog(this,
                e.getMessage());

    }
        
        
    }//GEN-LAST:event_loginButtonActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void bookServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookServiceActionPerformed
        // TODO add your handling code here:
        HomePage back = new HomePage ();
        back.setVisible(true);
        this.dispose(); // optional
    }//GEN-LAST:event_bookServiceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CustomerLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookService;
    private javax.swing.JLabel cLogin;
    private javax.swing.JLabel cMail;
    private javax.swing.JLabel cPassword;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField password;
    // End of variables declaration//GEN-END:variables
}
