/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ADMIN
 */
public class HomePage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HomePage.class.getName());

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
        this.setLocation(300, 150); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        projectTitle = new javax.swing.JLabel();
        cLogin = new javax.swing.JButton();
        cRegistratiion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        projectTitle.setBackground(new java.awt.Color(0, 0, 0));
        projectTitle.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        projectTitle.setForeground(new java.awt.Color(255, 255, 255));
        projectTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        projectTitle.setText("Vehical Service Center");
        projectTitle.setOpaque(true);
        getContentPane().add(projectTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, -1));

        cLogin.setBackground(new java.awt.Color(255, 204, 153));
        cLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cLogin.setText("Login");
        cLogin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cLogin.setBorderPainted(false);
        cLogin.addActionListener(this::cLoginActionPerformed);
        getContentPane().add(cLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 132, 37));

        cRegistratiion.setBackground(new java.awt.Color(255, 204, 153));
        cRegistratiion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cRegistratiion.setText("Register");
        cRegistratiion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cRegistratiion.addActionListener(this::cRegistratiionActionPerformed);
        getContentPane().add(cRegistratiion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 132, 37));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Downloads\\status track.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, -100, 610, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cRegistratiionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cRegistratiionActionPerformed
        // TODO add your handling code here:
        
         // Open Customer Registration form
        CustomerRegistration register = new CustomerRegistration();
        register.setVisible(true);

        this.dispose(); // optional
    }//GEN-LAST:event_cRegistratiionActionPerformed

    private void cLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cLoginActionPerformed
        // TODO add your handling code here:
        // open Customer Login Page
        CustomerLogin login = new CustomerLogin();
        login.setVisible(true);
         this.dispose(); // optional
         
         
         
         
         
         
         
         
         
         
        
        
         
    }//GEN-LAST:event_cLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HomePage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cLogin;
    private javax.swing.JButton cRegistratiion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel projectTitle;
    // End of variables declaration//GEN-END:variables
}
