/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ADMIN
 */
public class PaymentPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PaymentPage.class.getName());

    /**
     * Creates new form PaymentPage
     */
    public PaymentPage() {
        initComponents();
        this.setLocation(300, 150); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paymentPage = new javax.swing.JLabel();
        bookingID = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        amount = new javax.swing.JLabel();
        paymentMethod = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        bookService = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        paymentPage.setBackground(new java.awt.Color(204, 255, 204));
        paymentPage.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        paymentPage.setForeground(new java.awt.Color(255, 153, 102));
        paymentPage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        paymentPage.setText("Payment Page");
        paymentPage.setOpaque(true);
        getContentPane().add(paymentPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 330, 40));

        bookingID.setBackground(new java.awt.Color(153, 204, 255));
        bookingID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bookingID.setText("Booking ID");
        bookingID.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bookingID.setOpaque(true);
        getContentPane().add(bookingID, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 92, 114, 32));

        jTextField3.addActionListener(this::jTextField3ActionPerformed);
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 92, 217, 32));

        amount.setBackground(new java.awt.Color(255, 204, 255));
        amount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        amount.setText("Amount");
        amount.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        amount.setOpaque(true);
        getContentPane().add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 142, 114, 32));

        paymentMethod.setBackground(new java.awt.Color(255, 204, 255));
        paymentMethod.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        paymentMethod.setText("Payment Method");
        paymentMethod.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        paymentMethod.setOpaque(true);
        getContentPane().add(paymentMethod, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 192, 114, 32));

        jButton1.setBackground(new java.awt.Color(102, 204, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Pay Now");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 266, 188, 35));

        jTextField4.addActionListener(this::jTextField4ActionPerformed);
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 142, 217, 32));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "UPI", "Cards", "Digital Wallets", "Net Banking" }));
        jComboBox2.addActionListener(this::jComboBox2ActionPerformed);
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 192, 217, 33));

        bookService.setBackground(new java.awt.Color(204, 204, 255));
        bookService.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bookService.setText("<-- Back ");
        bookService.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bookService.addActionListener(this::bookServiceActionPerformed);
        getContentPane().add(bookService, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 85, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Downloads\\payemt page.jpeg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void bookServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookServiceActionPerformed
        // TODO add your handling code here:
       CustomerDashboard back = new CustomerDashboard ();
        back.setVisible(true);
        this.dispose(); // optional
    }//GEN-LAST:event_bookServiceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PaymentPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amount;
    private javax.swing.JButton bookService;
    private javax.swing.JLabel bookingID;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel paymentMethod;
    private javax.swing.JLabel paymentPage;
    // End of variables declaration//GEN-END:variables
}
