/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ADMIN
 */

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;


public class ServiceStatusTracking extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ServiceStatusTracking.class.getName());

    /**
     * Creates new form ServiceBooking
     */
    public ServiceStatusTracking() {
        initComponents();
        this.setLocation(300, 150); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        serviceStatusTracking = new javax.swing.JLabel();
        bookingID = new javax.swing.JLabel();
        serviceType = new javax.swing.JLabel();
        vehicleNumber = new javax.swing.JLabel();
        booking_id = new javax.swing.JTextField();
        vehicle_number = new javax.swing.JTextField();
        service_type = new javax.swing.JComboBox<>();
        checkStatusButton = new javax.swing.JButton();
        serviceType1 = new javax.swing.JLabel();
        lblStatus = new javax.swing.JTextField();
        bookService = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        serviceStatusTracking.setBackground(new java.awt.Color(204, 255, 255));
        serviceStatusTracking.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        serviceStatusTracking.setForeground(new java.awt.Color(255, 102, 102));
        serviceStatusTracking.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        serviceStatusTracking.setText("Service Status Tracking");
        serviceStatusTracking.setOpaque(true);
        getContentPane().add(serviceStatusTracking, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 340, -1));

        bookingID.setBackground(new java.awt.Color(255, 204, 153));
        bookingID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bookingID.setText("Booking ID");
        bookingID.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bookingID.setOpaque(true);
        getContentPane().add(bookingID, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 114, 30));

        serviceType.setBackground(new java.awt.Color(255, 204, 153));
        serviceType.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        serviceType.setText("Status ");
        serviceType.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        serviceType.setOpaque(true);
        getContentPane().add(serviceType, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 114, 30));

        vehicleNumber.setBackground(new java.awt.Color(255, 204, 153));
        vehicleNumber.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        vehicleNumber.setText("Vehicle Number");
        vehicleNumber.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        vehicleNumber.setOpaque(true);
        getContentPane().add(vehicleNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 114, 30));

        booking_id.addActionListener(this::booking_idActionPerformed);
        getContentPane().add(booking_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 217, 30));

        vehicle_number.addActionListener(this::vehicle_numberActionPerformed);
        getContentPane().add(vehicle_number, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 217, 30));

        service_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "General Service", "Oil Change", "Engine Repair", "Brake Service", "Battery Replacement", "Wheel Alignment", "AC Service", "Water Wash" }));
        getContentPane().add(service_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 217, 30));

        checkStatusButton.setBackground(new java.awt.Color(102, 204, 255));
        checkStatusButton.setForeground(new java.awt.Color(255, 255, 255));
        checkStatusButton.setText("Check Status");
        checkStatusButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        checkStatusButton.addActionListener(this::checkStatusButtonActionPerformed);
        getContentPane().add(checkStatusButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 178, 30));

        serviceType1.setBackground(new java.awt.Color(255, 204, 153));
        serviceType1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        serviceType1.setText("Service Type");
        serviceType1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        serviceType1.setOpaque(true);
        getContentPane().add(serviceType1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 114, 30));

        lblStatus.setText(" Not Checked");
        lblStatus.addActionListener(this::lblStatusActionPerformed);
        getContentPane().add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 217, 30));

        bookService.setBackground(new java.awt.Color(204, 204, 255));
        bookService.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bookService.setText("<-- Back ");
        bookService.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bookService.addActionListener(this::bookServiceActionPerformed);
        getContentPane().add(bookService, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Downloads\\Customer Dashbord 2.jpeg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-320, -110, -1, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void booking_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_booking_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_booking_idActionPerformed

    private void vehicle_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicle_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vehicle_numberActionPerformed

    private void checkStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkStatusButtonActionPerformed
        // TODO add your handling code here:
        // open Customer Login Page
//       CustomerDashboard homePage = new CustomerDashboard ();
//        homePage.setVisible(true);
//        this.dispose(); // optional


String bid = booking_id.getText();
    String vno = vehicle_number.getText();
    String stype = service_type.getSelectedItem().toString();

    try {

        Connection con = DBConnection.getConnection();

        String sql =
        "SELECT status FROM service_status "
      + "WHERE booking_id=? "
      + "AND vehicle_number=? "
      + "AND service_type=?";

        PreparedStatement pst =
                con.prepareStatement(sql);

        pst.setInt(1, Integer.parseInt(bid));
        pst.setString(2, vno);
        pst.setString(3, stype);

        ResultSet rs = pst.executeQuery();

        if(rs.next()) {

            lblStatus.setText(
                    rs.getString("status"));

        } else {

            JOptionPane.showMessageDialog(
                    this,
                    "Record Not Found");

            lblStatus.setText("Not Found");
        }

        con.close();

    } catch(Exception e) {

        JOptionPane.showMessageDialog(
                this,
                e.getMessage());

    }



    }//GEN-LAST:event_checkStatusButtonActionPerformed

    private void lblStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblStatusActionPerformed

    private void bookServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookServiceActionPerformed
        // TODO add your handling code here:
       CustomerDashboard back = new CustomerDashboard ();
        back.setVisible(true);
        this.dispose(); // optional
    }//GEN-LAST:event_bookServiceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ServiceStatusTracking().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookService;
    private javax.swing.JLabel bookingID;
    private javax.swing.JTextField booking_id;
    private javax.swing.JButton checkStatusButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField lblStatus;
    private javax.swing.JLabel serviceStatusTracking;
    private javax.swing.JLabel serviceType;
    private javax.swing.JLabel serviceType1;
    private javax.swing.JComboBox<String> service_type;
    private javax.swing.JLabel vehicleNumber;
    private javax.swing.JTextField vehicle_number;
    // End of variables declaration//GEN-END:variables
}
