/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ADMIN
 */

import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;


public class ServiceBooking extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ServiceBooking.class.getName());

    /**
     * Creates new form ProfilePage
     */
    public ServiceBooking() {
        initComponents();
        this.setLocation(300, 150); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        serviceBooking = new javax.swing.JLabel();
        vehicleNumber = new javax.swing.JLabel();
        booking_id = new javax.swing.JTextField();
        bookServiceButton = new javax.swing.JButton();
        vehicleName = new javax.swing.JLabel();
        serviceDate = new javax.swing.JLabel();
        serviceType = new javax.swing.JLabel();
        problemDiscription = new javax.swing.JLabel();
        vehicle_name = new javax.swing.JTextField();
        vehicle_number = new javax.swing.JTextField();
        problem_description = new javax.swing.JTextField();
        service_type = new javax.swing.JComboBox<>();
        bookService = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        serviceBooking.setBackground(new java.awt.Color(255, 153, 153));
        serviceBooking.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        serviceBooking.setForeground(new java.awt.Color(255, 255, 255));
        serviceBooking.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        serviceBooking.setText("Service Booking");
        serviceBooking.setOpaque(true);
        getContentPane().add(serviceBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 400, -1));

        vehicleNumber.setBackground(new java.awt.Color(255, 204, 153));
        vehicleNumber.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        vehicleNumber.setText("Vehicle Number");
        vehicleNumber.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        vehicleNumber.setOpaque(true);
        getContentPane().add(vehicleNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 133, 32));

        booking_id.addActionListener(this::booking_idActionPerformed);
        getContentPane().add(booking_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 44, 217, 32));

        bookServiceButton.setBackground(new java.awt.Color(102, 204, 255));
        bookServiceButton.setForeground(new java.awt.Color(255, 255, 255));
        bookServiceButton.setText("Book Service");
        bookServiceButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bookServiceButton.addActionListener(this::bookServiceButtonActionPerformed);
        getContentPane().add(bookServiceButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 193, 36));

        vehicleName.setBackground(new java.awt.Color(255, 204, 153));
        vehicleName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        vehicleName.setText("Vehicle Name");
        vehicleName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        vehicleName.setOpaque(true);
        getContentPane().add(vehicleName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 133, 32));

        serviceDate.setBackground(new java.awt.Color(255, 204, 153));
        serviceDate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        serviceDate.setText("Booking ID");
        serviceDate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        serviceDate.setOpaque(true);
        getContentPane().add(serviceDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 44, 133, 32));

        serviceType.setBackground(new java.awt.Color(255, 204, 153));
        serviceType.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        serviceType.setText("Service Type");
        serviceType.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        serviceType.setOpaque(true);
        getContentPane().add(serviceType, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 133, 32));

        problemDiscription.setBackground(new java.awt.Color(255, 204, 153));
        problemDiscription.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        problemDiscription.setText("Problem Description");
        problemDiscription.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        problemDiscription.setOpaque(true);
        getContentPane().add(problemDiscription, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 133, 32));

        vehicle_name.addActionListener(this::vehicle_nameActionPerformed);
        getContentPane().add(vehicle_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 217, 32));

        vehicle_number.addActionListener(this::vehicle_numberActionPerformed);
        getContentPane().add(vehicle_number, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 217, 32));

        problem_description.addActionListener(this::problem_descriptionActionPerformed);
        getContentPane().add(problem_description, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 217, 32));

        service_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "General Service", "Oil Change", "Engine Repair", "Brake Service", "Battery Replacement", "Wheel Alignment", "AC Service", "Water Wash" }));
        getContentPane().add(service_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 217, 30));

        bookService.setBackground(new java.awt.Color(204, 204, 255));
        bookService.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bookService.setText("<-- Back ");
        bookService.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bookService.addActionListener(this::bookServiceActionPerformed);
        getContentPane().add(bookService, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 85, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Downloads\\status track.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void booking_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_booking_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_booking_idActionPerformed

    private void bookServiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookServiceButtonActionPerformed
        // TODO add your handling code here:
        CustomerDashboard homePage = new CustomerDashboard ();
        homePage.setVisible(true);
         this.dispose(); // optional
         
    String bid = booking_id.getText();
    String vname = vehicle_name.getText();
    String vnumber = vehicle_number.getText();
    String stype = service_type.getSelectedItem().toString();
    String problem = problem_description.getText();

    if(bid.isEmpty() || vname.isEmpty() || vnumber.isEmpty() || problem.isEmpty()) {

        JOptionPane.showMessageDialog(this,
                "Please Fill All Fields");

        return;
    }

    try {

        Connection con = DBConnection.getConnection();

        String sql =
        "INSERT INTO service_booking VALUES(?,?,?,?,?)";

        PreparedStatement pst =
                con.prepareStatement(sql);

        pst.setInt(1, Integer.parseInt(bid));
        pst.setString(2, vname);
        pst.setString(3, vnumber);
        pst.setString(4, stype);
        pst.setString(5, problem);

        int result = pst.executeUpdate();

        if(result > 0) {

            JOptionPane.showMessageDialog(this,
                    "Service Booked Successfully");

            booking_id.setText("");
            vehicle_name.setText("");
            vehicle_number.setText("");
            problem_description.setText("");

        }

        con.close();

    } catch(Exception e) {

        JOptionPane.showMessageDialog(this,
                e.getMessage());

    }
    }//GEN-LAST:event_bookServiceButtonActionPerformed

    private void vehicle_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicle_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vehicle_nameActionPerformed

    private void vehicle_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicle_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vehicle_numberActionPerformed

    private void problem_descriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_problem_descriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_problem_descriptionActionPerformed

    private void bookServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookServiceActionPerformed
        // TODO add your handling code here:
        CustomerDashboard back = new CustomerDashboard ();
        back.setVisible(true);
        this.dispose(); // optional

    }//GEN-LAST:event_bookServiceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ServiceBooking().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookService;
    private javax.swing.JButton bookServiceButton;
    private javax.swing.JTextField booking_id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel problemDiscription;
    private javax.swing.JTextField problem_description;
    private javax.swing.JLabel serviceBooking;
    private javax.swing.JLabel serviceDate;
    private javax.swing.JLabel serviceType;
    private javax.swing.JComboBox<String> service_type;
    private javax.swing.JLabel vehicleName;
    private javax.swing.JLabel vehicleNumber;
    private javax.swing.JTextField vehicle_name;
    private javax.swing.JTextField vehicle_number;
    // End of variables declaration//GEN-END:variables
}
