/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ADMIN
 */

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
public class ServiceHistory extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ServiceHistory.class.getName());

    /**
     * Creates new form ServiceHistory
     */
    public ServiceHistory() {
        initComponents();
        this.setLocation(300, 150); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        paymentPage = new javax.swing.JLabel();
        checkStatus = new javax.swing.JButton();
        bookService = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        historyTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        paymentPage.setBackground(new java.awt.Color(255, 204, 153));
        paymentPage.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        paymentPage.setForeground(new java.awt.Color(255, 102, 102));
        paymentPage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        paymentPage.setText("Service History");
        paymentPage.setOpaque(true);
        getContentPane().add(paymentPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 340, 40));

        checkStatus.setBackground(new java.awt.Color(255, 153, 153));
        checkStatus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        checkStatus.setText("Check History");
        checkStatus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        checkStatus.addActionListener(this::checkStatusActionPerformed);
        getContentPane().add(checkStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 188, 35));

        bookService.setBackground(new java.awt.Color(204, 204, 255));
        bookService.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bookService.setText("<-- Back ");
        bookService.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bookService.addActionListener(this::bookServiceActionPerformed);
        getContentPane().add(bookService, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 85, -1));

        historyTable.setBackground(new java.awt.Color(204, 255, 255));
        historyTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        historyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Booking ID", "Service Type", "Amount ", "Status "
            }
        ));
        historyTable.setSelectionBackground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(historyTable);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 490, 150));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Downloads\\Customer Dashbord 2.jpeg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -640, 530, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkStatusActionPerformed
        // TODO add your handling code here:
        
        
        
        
         try {

        Connection con = DBConnection.getConnection();

        String sql = "SELECT * FROM service_history";

        PreparedStatement pst = con.prepareStatement(sql);

        ResultSet rs = pst.executeQuery();

        DefaultTableModel model =
                (DefaultTableModel) historyTable.getModel();

        model.setRowCount(0);

        while (rs.next()) {

            model.addRow(new Object[]{

                rs.getInt("booking_id"),
                rs.getString("service_type"),
                rs.getDouble("amount"),
                rs.getString("status")

            });

        }

        con.close();

    } catch (Exception e) {

        javax.swing.JOptionPane.showMessageDialog(this,
                e.getMessage());

    }
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_checkStatusActionPerformed

    private void bookServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookServiceActionPerformed
        // TODO add your handling code here:
        CustomerDashboard back = new CustomerDashboard ();
        back.setVisible(true);
        this.dispose(); // optional
    }//GEN-LAST:event_bookServiceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ServiceHistory().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookService;
    private javax.swing.JButton checkStatus;
    private javax.swing.JTable historyTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel paymentPage;
    // End of variables declaration//GEN-END:variables
}
